### ISSUE TITLE
the car is steering to the left

### ISSUE THREAD

**Issue by jakob91** [djyt/cannonball#22]
Hello, it seems no matter which controller I plug in the car steer to the left randomly, in some straight lines it seems correct, then a few seconds later the left-steer is back again. It aims to the left as well using a DualShock3 gamepad but somehow with a gamepad I'm unable to create a deadzone in the configuration file (or maybe I have to input some specific command about adding a deadzone with said controller I have no clue). It doesn't seem to be a calibration issue as moving completely to the end of the axes doesn't seem to change anything. Very much like Cannonball if it wouldn't be of this annoying bug, thank you for your work on it.

**Comment by djyt** [comment]
This is quite an old bug now. Can you confirm whether you still experience this issue on the latest beta version?
https://drive.google.com/file/d/1mfXm9F7hWdctkvGPPtnMAclKA-yOUAk5/view?usp=sharing
