### ISSUE TITLE
Retropie cannonball disappears from ports list

### ISSUE THREAD

**Issue by ianpaulstone** [djyt/cannonball#24]
Hi there,

I've definitely got cannonball installed. It's suddenly disappeared from the ports list since I've scraped all the games on my system. This happened on another pi too... any ideas how to get it back please?

Thanks

Ian

**Comment by djyt** [comment]
I don't maintain the Pi port unfortunately, it will have been created by someone else (who I've never spoken to), so this isn't a bug with the main project as such.
