### ISSUE TITLE
Music runs slightly slow

### ISSUE THREAD

**Issue by zenzero-2001** [djyt/cannonball#25]
Hello

I've compiled Cannonball version 0.3 for Linux Mint 14.04 64bit. I have noticed that the music runs a tiny bit too slow. I verified this by capturing the sound test output with ALSA and comparing the length of Magical Sound Shower with the wave output of the VGM version and with various CD releases.

Love what you have done with the game :-)

**Comment by djyt** [comment]
Verified as an issue. 

I have not, as yet, been able to track down what is causing this.

**Comment by J1mbo** [comment]
I think the CDs must have been re-mastered. The speed can be matched by increasing the sample rate to about 45KHz, but the pitch is then quite a lot out (maybe a semi-tone).

**Comment by gingerbeardman** [comment]
What about comparing to the original arcade hardware?

**Comment by J1mbo** [comment]
Compared to a YouTube video, it does indeed run the same amount slow.

**Comment by TwoLeaves** [comment]
Hi all. J1mbo, do you mean by the above comment that the Cannonball engine runs the music at the same speed as the original arcade machine (i.e. both "slow" compared to the CD)? If so I'm not sure that's correct, or perhaps there are multiple versions of the arcade machine. When I look at videos of the original machine on YouTube the music seems to run at 126bpm as opposed to this engine which runs at about 120bpm. That is on the "Passing Breeze" track, a good example of which (on original hardware) is here: [https://youtu.be/8kM467EHDxE?t=622](https://youtu.be/8kM467EHDxE?t=622).

**Comment by J1mbo** [comment]
Sorry for the lack of clarity. Yes I agree, the arcade cab is the same as the CD based on what I can find on YouTube.

**Comment by J1mbo** [comment]
Based on the numbers, my guess is that something is counting to 64 instead of 60.

**Comment by J1mbo** [comment]
The game timers (without fixed applied) appear to be true to the arcade. I haven't been able to alter the music playback speed at all, this one remains a mystery.

**Comment by zenzero-2001** [comment]
Maybe it is something to do with the segapcm driver? The comment in the code says it is altered from the MAME version to output at a fixed rate of 44.1kHz, maybe there is an issue here? Also, I notice that the clock parameter for the SegaPCM constructor appears to be unused.

It is just an idea, I'm probably barking up the wrong tree.

**Comment by J1mbo** [comment]
It's related to the sample rate as that seems to be the only way to affect the playback speed. But it also looks like this bug was first noted in 2008 in MAME and noone has been able to fix it yet: https://mametesters.org/view.php?id=7211

**Comment by zenzero-2001** [comment]
@J1mbo Thanks for fixing this :-)

**Comment by J1mbo** [comment]
@zenzero-2001 no problem, I have further updated my fork today which I believe correctly fixes this issue. There are numerous other changes and performance improvements too, most significantly runs the video rendering in a separate thread.

**Comment by djyt** [comment]
This is now fixed in the latest source chcek-in. And I really wish I'd read this thread first. :)
