### ISSUE TITLE
Any futher update?

### ISSUE THREAD

**Issue by PPastene** [djyt/cannonball#27]
Hi

I was wondering if this will continue it's developnment. I know that the most bugs from the original arcade are fixed and there's a lot of improvement, but this has a lot of potencial. Maybe some telemetry output for motion simulator or haptic HID, an online ranking, ghost time attack? And it will sound crazy but try to recreate Turbo Outrun or OutRunners

Anyway, hope to see some update soon 👍

**Comment by djyt** [comment]
Not a bug, but right now I've been working on some other projects. http://reassembler.blogspot.com has details.
