### ISSUE TITLE
Implement SDL 2 Haptic Support

### ISSUE THREAD

**Issue by baritonomarchetto** [djyt/cannonball#28]
Yes Chris, I am still in the need for the rumble to be implemented! :)

Cannonball could be the best outrun version out there (well, it just is!), but it is still missing one of the feature that made the cabinet memorable: RUMBLE!

I know the force feedback is supported, but... rumble?! My rumble equipped arcade cabinet NEEDS this feature (ah, no: that's me!).

**Comment by djyt** [comment]
Yep I'm going to look into implementing this shortly.

**Comment by djyt** [comment]
**d72b99d - Add basic rumble support for gamepads**

I've checked in a first iteration of this. It uses the original Standard Upright motor code to trigger a basic rumble effect.
I haven't tested in detail yet.
