### ISSUE TITLE
Unable to build current on macOS 10.13.1

### ISSUE THREAD

**Issue by ProxyCell** [djyt/cannonball#30]
This is the result after I "make" - gets all the way down to the linker and breaks
I have the latest boost and sdl installed. the cmake ran fine and I used the cmake file for macosx that is provided.

> [ 98%] Building CXX object CMakeFiles/cannonball.dir/Users/jackfeschuk/Documents/github/cannonball/src/main/engine/audio/osoundint.cpp.o
> [100%] Linking CXX executable cannonball
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
> Undefined symbols for architecture x86_64:
>   "_main", referenced from:
>       start in crt1.10.6.o
>      (maybe you meant: __ZN4OHud13draw_main_hudEv, _SDL_main )
> **ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [cannonball] Error 1
> make[1]: *** [CMakeFiles/cannonball.dir/all] Error 2
> make: *** [all] Error 2**

**Comment by Clever-Boy** [comment]
Same error. 

Is there a solution for this.

**Comment by Clever-Boy** [comment]
I finally was able to compile it. Added two more files in the SDL directory and updated them CMakeLists.txt in CMake directory.  Listed below

Also updated main.cpp  to include 
int SDL_main(int argc, char* argv[])    

-- CMakeLists.txt --

else()  #Using legacy, unmantained SDL1.x
	if(OPENGL)
	    set(src_sdl
		"${main_cpp_base}/sdl/SDLMain.h"   -- added
		 ... other header files
		"${main_cpp_base}/sdl/SDLMain.m" -- added
                ... other cpp files
		)   
	else()
	    set(src_sdl
                "${main_cpp_base}/sdl/SDLMain.h"  -- same here
		... same here
		"${main_cpp_base}/sdl/SDLMain.m"
		.. same here
		)

rebuild again. This should work for SDL2 as well. Not tested.

**Comment by ProxyCell** [comment]
Hey @Clever-Boy ! This is working for me too!

Concerning SDL2:
I couldn't find an SDLMain.m or SDL_Main.m -> could only locate SDL_Main.h would I placed in there.

Anyways, everything works on macOS it seems now. I even added the icon from the /res folder.

**Comment by Judder** [comment]
@Clever-Boy are you compiling SDL1 from source?

I seem to have the problem on High Sierra where CGDirectPaletteRef has been removed and thus won't compile

```
In file included from ../src/video/quartz/SDL_QuartzEvents.m:24:
../src/video/quartz/SDL_QuartzVideo.h:94:5: error: unknown type name 'CGDirectPaletteRef'
    CGDirectPaletteRef palette;            /* palette of an 8-bit display */
```

@ProxyCell 

Compiling with SDL2 installed, cannonball doesn't like the SLD2 library - looking for SDL1 with default configuration. Any changes needed here?

```
$ cmake -G "Unix Makefiles" -DTARGET:STRING=macosx ../cmake
CMake files for macosx found, using macosx.cmake
-- Architecture: x86_64
CMake Error at /opt/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SDL (missing: SDL_LIBRARY) (found version "2.0.4")
```
