### ISSUE TITLE
No clear instructions on Linux building

### ISSUE THREAD

**Issue by HeartDruid1** [djyt/cannonball#32]
I tried the mentioned build instructions on Linux Mint and it returned an error due to a missing DirectX SDK

**Comment by carstene1ns** [comment]
Default target is windows, yes, but the README mentions you can override with `-DTARGET=`.
In your case, try `debian` (for SDL1) or `sdl2` targets, but clean the CMake cache before retrying.
I am using `-DTARGET=sdl2` for my Arch Linux package and it works.

**Comment by HeartDruid1** [comment]
My bad. Thank you @carstene1ns , I guess I didn't read the README well enough.
