### ISSUE TITLE
Not an issue but asking for clarification :)

### ISSUE THREAD

**Issue by HeartDruid1** [djyt/cannonball#33]
I built Cannonball on Linux and I'm having some trouble getting multiple things to work due to unclear documentation. I'm new to all this so bear with me. I'm having trouble getting custom music to work and having issues with the patched samples. I downloaded the ROMs and I can't seem to get them to load. I put them in the same folder with the rest of the roms and for the custom music. I have the .wav file and I modified the config.xml document to add it in but it doesn't say where the .wav file should be. If someone could help clarify all this I would appreciate it.

**Comment by djyt** [comment]
WAVs go in the same folder as the executable :)
