### ISSUE TITLE
About Resolution

### ISSUE THREAD

**Issue by welintron** [djyt/cannonball#34]
Is it possible to run Cannonball in native resolution? I want to run this game in my arcade cabinet but with the same resolution as the original game (I'm using ArcadeVGA who allows that)

**Comment by gingerbeardman** [comment]
I'm pretty sure it already does, as long as you do not specify widescreen or hi-resolution modes.

**Comment by djyt** [comment]
Yes it runs at 320x224. Support for original OutRun arcade hardware (and CRTs) is coming shortly via the SmartPi interface.
