### ISSUE TITLE
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1006:  9719 Illegal i nstruction

### ISSUE THREAD

**Issue by nibio74** [djyt/cannonball#36]
This error happens by launching the game from emulationstation with retropie 4.4 on rpi1:

runcommand,log

Parameters:
Executing: pushd /opt/retropie/ports/cannonball; /opt/retropie/ports/cannonball/
cannonball; popd
/opt/retropie/ports/cannonball ~/RetroPie/roms/ports
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1006:  9719 Illegal i
nstruction     /opt/retropie/ports/cannonball/cannonball
~/RetroPie/roms/ports

**Comment by SinisterSpatula** [comment]
I also got the same error on Pi zero which uses the same CPU/compiler flag.   Bummer :(

**Comment by djyt** [comment]
I can cross-compile compile fine on the Pi4 and have checked in the cmake file I'm using to do this. It's running at 60fps with no issues.
