### ISSUE TITLE
About the license...

### ISSUE THREAD

**Issue by gameblabla** [djyt/cannonball#37]
Hello Cannonball devs, nice project !
However, when i looked at the license, it wasn't pretty to say the least...

> * Redistributions may not be sold, nor may they be used in a commercial
> product or activity.

I honestly wonder why this restriction is necessary ? Sega would not allow bundling it with outrun anyway and this prevents anyone from making a libre clone. (like Freedoom)
As for the latter, well, it basically implies i can't use it on my computer, it was sold as a commercial product after all... which means that i can be on the receiving end of a lawsuit from you by simply using it. w_w

Please, switch to another license like the GPLv3, Apache or even the Expat license.
Thank you

**Comment by carstene1ns** [comment]
> As for the latter, well, it basically implies i can't use it on my computer, it was sold as a commercial product after all... which means that i can be on the receiving end of a lawsuit from you by simply using it. w_w

this is plainly bs.

**Comment by gameblabla** [comment]
> this is plainly bs.
Well i hope it is. Either way, i don't know how to interpret it and i don't feel like this is necessary. Of course, you can choose not to listen...

**Comment by MichaelRPowell** [comment]
Yeah, this seems like a complete misreading of the license. You are really stretching the words to imply that buying a computer to run the software equates to a commercial activity when using the software. 

In this situation a "commercial product" is simple, like releasing it as a paid application on a digital store or in a physical store. A commercial activity, while vague in this situation, would likely mean promoting and running a paid tournament/contest for profit focusing on or featuring this software. An alternative example would be setting up a machine to run the software and charging people per play, like an arcade machine. Those are probably decent examples of "commercial activities".

I am not a legal expert, but thinking that running this software on a computer you purchased is a commercial activity seems like a complete misreading of the text.

**Comment by gameblabla** [comment]
I was saying that due to the way it was worded. Of course, if he was planning to forbid making profit on Cannonball then sure but taking your point as an example, even releasing it for free on the Google Play could be considered a "commercial activity". Nowhere it is mentioned wherever it is for profit or not. 

That does not make it right though. But of course a free software license isn't appealing to the developers, then i suppose i could only have my tears and their great willing as a last resort...

@carstene1ns Next time, i would appreciate a more detailed answer, thank you.

**Comment by djyt** [comment]
I think the license is pretty clear. It's based on the former MAME license and the wording is pretty much identical. Don't sell CannonBall.
