### ISSUE TITLE
Wii Port - Retard when pressing buttons on Classic Controller

### ISSUE THREAD

**Issue by SieKensou** [djyt/cannonball#39]
I have found this awesome port for the Wii:
http://wiibrew.org/wiki/OutRun_(Cannonball_engine)

And it's really great to have a way to play this great engine of this great game on the Wii. I just tested the Classic Controller but I noticed it has some high retard when I press a button or the D-Pad. It needs a lot of time from when I press the brake button until the brake light of the car looks on and the car starts to brake. The same with all other buttons and the D-Pad. It works perfect to move the car with the analog stick.

**Comment by djyt** [comment]
I don't maintain the Wii port unfortunately. I'd suggest writing to the author directly.
