### ISSUE TITLE
Feature request: flatpak!

### ISSUE THREAD

**Issue by unholyeyebrows** [djyt/cannonball#40]
Hi

What are the possibilities of packaging Cannonball in a flatpak for delivery via flathub?

Thanks in advance
Nick

**Comment by djyt** [comment]
I've no idea what this is :)

**Comment by denilsonsa** [comment]
Flatpak is a way to distribute packages in a distro-agnostic way. Flathub is a repository of flatpaks. It's also the easiest way to install apps on the Steam Deck (besides Steam itself).

* https://docs.flatpak.org/en/latest/publishing.html
* https://docs.flathub.org/docs/for-app-authors/submission/
