### ISSUE TITLE
120fps option

### ISSUE THREAD

**Issue by Tatsuya79** [djyt/cannonball#41]
Hi, thanks for that great engine!

I added a 120fps option in the libretro core for RetroArch: 
https://github.com/libretro/cannonball/pull/6/files

I hope it's not too wrong and perhaps some parts could be used here to add that option.
Just wanted to let you know that.

**Comment by djyt** [comment]
I did start the 120fps code as you probably saw when I was first developing CannonBall. Then I realised my monitor only refreshed at 60hz so was largely pointless for me! 

I think the main to be careful of is ensuring the collision code still works at 120fps. From memory, there's the possibility of collisions not being detected at higher frame rates. But if everything seems fine then you're good. I'll close this for now, but if I ever get a decent monitor and graphics card I'll look into 120fps.
