### ISSUE TITLE
Car only accelerates when gas is released

### ISSUE THREAD

**Issue by Namco51** [djyt/cannonball#42]
When the game starts the accelerator is pegged all the time. I have to press it down for it to not be engaged. I have analog controls turned on and I have my gas and brake mapped correctly as axis 2 and 3. Most other apps require me to set axis 3 as inverted in order to work correctly, but cannonball expects axis 2 to be inverted. Brake (axis 3) works correctly, but I have to hold down accel (as axis 2) in order to coast. 

Is there any way to invert an axis in cannonball settings?

**Comment by WildPenquin** [comment]
I can confirm this issue. Accelerator axis is inverted in cannonball. This is on Linux, PS3 controller.

**Comment by djyt** [comment]
I believe this is now fixed (in the latest source code at least). There was an issue with the SDL 2 migration that might have impacted this. 

I'll compile a new binary in due course.
