### ISSUE TITLE
Controller issue - Constant slight steering to the left and slight acceleration

### ISSUE THREAD

**Issue by WelfzTwingoFurs** [djyt/cannonball#52]
I've seen that some people also have had this issue, but I still can't seem to find an answer to it. With my controller plugged and analog enabled, the car will always be steering to the left a little bit, and accelerating to 68-69km/h. The game's completely awesome, but man, that makes it difficult to enjoy!

**Comment by djyt** [comment]
If this is from your own compile, as opposed to the compiled binary, try compiling again.

There was a controller related problem which I've now fixed related to SDL2.
