### ISSUE TITLE
Added linux force feedback support 

### ISSUE THREAD

**Issue by Ismas** [djyt/cannonball#56]
Hi there!
Just added force feedback support for linux. Pull is requested. Please help me testing by checking it with your devices. You should enable and configure it in config.xml and it should automatically detect it. Only one device supported.

https://github.com/Ismas/cannonball/tree/linux_forcefeedback_support

**Comment by djyt** [comment]
Cool, thanks for doing this. My plan is to investigate the SDL2 force feedback support at some point. I've no idea if it's any good, but I'd like to remove the antique DirectX8 code entirely and have a better cross-platform solution.
