### ISSUE TITLE
run the game at 320x224

### ISSUE THREAD

**Issue by ditters90** [djyt/cannonball#60]
hi! let me just start by saying that i love this game!
the problem is that the game always opens up at the desktop resolution.. i want to force the game to open at 320x224, and i dont know the way to do that in the config.xml file.. 
(im using a real arcade monitor, and before i open the game i always have to change the dektop res..)

**Comment by djyt** [comment]
In config.xml
Set scale to 1.
Set mode to 0.

Then you can run in full-screen at 320x224.

Yes it runs at 320x224. Support for original OutRun arcade hardware (and CRTs) is coming shortly via the SmartPi interface.
