### ISSUE TITLE
pausing as game progresses on Windows 10

### ISSUE THREAD

**Issue by mlynngh** [djyt/cannonball#62]
Using the  v.03 (Nov 2014) build on Windows 10 (x64) the following effects are occurring:

OpenGL: after level 2 (Gateway, Devil's Canyon) the music and screen update slows down.
Software Rendering: on any level the game can pause for up-to 2 seconds. A driver exception is thrown and logged in EventVwr.
Display driver igfx stopped responding and has successfully recovered.

This occurs at original frame rate, 30FPS and 60FPS. The average GPU processor time usage is only 4% so this is unexpected behaviour.

System info:
OS: Windows 10 build 10.0.18363.959 (x64)
Processor: Intel N4200 @ 1.1GHz (4 core)
Memory: 4Gb DDR3
HDD: 500Gb SSD
Machine: Acer Aspire E5 15
Display Driver: Intel(R) HD Graphics
Main Driver: igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll 
Display Memory: 128Mb

The memory usage is not continually increasing. The OpenGL build resumes normal speed when the game ends (out of time) or goes back to attract mode.

**Comment by mlynngh** [comment]
Further information: A reboot seemed to cure this issue but I am suspecting that this may be an issue with the Intel HD Graphics driver and not the game code.

**Comment by djyt** [comment]
Can't reproduce this.
