### ISSUE TITLE
Can't compile in Ubuntu Mate 20.04 because cmake is too old

### ISSUE THREAD

**Issue by cpcbegin** [djyt/cannonball#66]
Cannonball can't compile in latest Ubuntu LTS due it requires CMake 3.18 and here is still version 3.16.3.

**Comment by cpcbegin** [comment]
I change cmake to new one but I get some linking errors:
`[100%] Linking CXX executable cannonball
/usr/bin/ld: no se puede encontrar -lopengl32
/usr/bin/ld: no se puede encontrar -lglu32
/usr/bin/ld: no se puede encontrar -ldxguid
/usr/bin/ld: no se puede encontrar -ldinput8
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cannonball.dir/build.make:838: cannonball] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/cannonball.dir/all] Error 2
make: *** [Makefile:103: all] Error 2`

**Comment by djyt** [comment]
You are trying to compile against a Windows cmake file. You need to make one for your system.

**Comment by flexiondotorg** [comment]
@cpcbegin Ubuntu MATE developer here :wave: 

You can installer newer `cmake` version from the Snap store. For example, this is how you can install `cmake` 3.18.

   snap install cmake --channel 3.18/stable --classic

You can view what other `cmake` version are available with:

  snap info cmake

I've made a snap of Cannonball, you can find it here:

  * https://snapcraft.io/cannonball

**Comment by djyt** [comment]
Thank you @flexiondotorg
