### ISSUE TITLE
Roms unsync with latest mame (0.226)

### ISSUE THREAD

**Issue by LodanZark** [djyt/cannonball#69]
The "epr-10381a.132" got renamed to "epr-10381b.132" and the "epr-10381.132" (outrundx) no longer exists, due having the same hashes as "epr-10381b.132" which it's located in parent ROM.

**Comment by djyt** [comment]
I will look into this.

**Comment by LodanZark** [comment]
The last changes can be found here: https://github.com/mamedev/mame/blob/master/src/mame/drivers/segaorun.cpp

**Comment by djyt** [comment]
Thanks. I'm ideally going to load everything by CRC scanning the directory, rather than relying on file names. 
MAME changes these all the time and it will just cause confusion.
I'm aiming to work on this in the next few days :)

**Comment by LodanZark** [comment]
If you're familiar to using rom managers tools like clrmamepro, maybe this dat\xml file will be useful to you:
[MAME 0.229 ROMs (split).zip](https://github.com/djyt/cannonball/files/6078956/MAME.0.229.ROMs.split.zip)

**Comment by djyt** [comment]
Cool. Same ROMs, just seems the MAME devs rename them every other week. 

Once I switch to CRC32 based loading it won't matter what the filenames are.

**Comment by djyt** [comment]
Checked in CRC32 based file loading. Searches for CRC32 value, not the file name itself.
