### ISSUE TITLE
I change cmake version in Ubuntu 20.04 but compilation still fails

### ISSUE THREAD

**Issue by cpcbegin** [djyt/cannonball#70]
I compile in Ubuntu Mate 20.04 with these commands:
```
source ../commonscripts/makeopenchangetodir.sh /opt/linuxemus
sudo apt install -y build-essential pip3 libsdl2-dev git libboost-dev libopengl-dev libglu1-mesa-dev
sudo apt remove -y cmake
sudo pip3 install cmake --upgrade
git clone --recurse-submodules https://github.com/djyt/cannonball
cd cannonball
mkdir build
cd build
cmake -DTARGET:STRING=sdl2 ../cmake
```
But I get this error:
```
/usr/bin/ld: no se puede encontrar -lopengl32
/usr/bin/ld: no se puede encontrar -lglu32
/usr/bin/ld: no se puede encontrar -ldxguid
/usr/bin/ld: no se puede encontrar -ldinput8
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cannonball.dir/build.make:838: cannonball] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/cannonball.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

**Comment by cpcbegin** [comment]
Finally I get compile Cannonball wieth cmake included in Ubuntu 20.04 return to previous commit:
`git reset --hard b6aa525ddd552f96b43b3b3a6f69326a277206bd`
So I think there is a regression.

**Comment by djyt** [comment]
You are trying to compile against a Windows cmake file. You need to make one for your system.

**Comment by cpcbegin** [comment]
I think you might add the makefile for GNU/Linux again.

**Comment by djyt** [comment]
The CMAKE system has been completely overhauled, as it was a complete mess before. 

The only Linux target I've currently tried is the Raspberry Pi 4. The CMAKE file was trivial, so it is hopefully easy to make one for Linux:
https://github.com/djyt/cannonball/blob/master/cmake/pi4-opengles.cmake

**Comment by djyt** [comment]
I've added a cmake Linux target that was submitted. Whether it works probably depends on your distro, but give it a go.
