### ISSUE TITLE
Non interlaced resolution compatibility

### ISSUE THREAD

**Issue by baritonomarchetto** [djyt/cannonball#81]
Hi Chris, I have noticed that the new engine (v032) only runs with interlaced resolutions. Could a resolution of 320x240 (or even better the original resolution) be supported in future releases?

Thanks for resuming the development of this great project!

**Comment by djyt** [comment]
It runs at 320x240. I have it running here on a CRT via the Pi4.

**Comment by baritonomarchetto** [comment]
Those are exactly the settings I have, but probably it's a groovymame fault ( or better, my fault in setting resolutions up) even if mame's ooutrunruns at native resolution without issue here

**Comment by djyt** [comment]
How do you mean a GroovyMAME fault? I don't understand the connection between CannonBall and GroovyMAME.

**Comment by baritonomarchetto** [comment]
No sorry: I meant CRT emudrivers. I should stop working and writing posts at the same time :D

**Comment by baritonomarchetto** [comment]
Thinking at this, I has no problems running cannonball (2.2 IIRW) on my old pc with CRT emudrivers 1.2. Now I use super resolutions with v2 drivers. What do you think, would this be the culript? Would it be possible to add an option to set a user/custom resolution so that one can toy with that option? :D
