### ISSUE TITLE
LIbretro port integration

### ISSUE THREAD

**Issue by vanfanel** [djyt/cannonball#85]
Hi!

Seeing that there is some interest on Cannonball supporting advanced shaders (it's just natural as we all remember OutRun on arcade CRTC monitors), and since the libretro port isn't getting much love these days, what about integrating libretro support?
That would bring immediate support for the finest shaders in the opensource world!

The libretro platform is already implemented in old Cannonball, and seems to be pretty much self-contained. It's here:

https://github.com/libretro/cannonball/tree/master/src/main/libretro

@djyt What are your thoughts on this?
There are other interesting implications, like no libboost dependency, which is desirable as libboost is a VERY big dependency for a lightweight engine like this.

**Comment by djyt** [comment]
The entire CannonBall executable is about 400k uncompressed and would fit on a floppy disk, so I'm not too concerned about boost causing bloatware. I only use the header libraries. 

Right now I'm working on some other features and projects so have no immediate plans to support libretro, not have I ever used it. Maybe in the future :)
