### ISSUE TITLE
no way to edit last letter if entered wrong

### ISSUE THREAD

**Issue by yepyepyep4711** [djyt/cannonball#88]
Hello,

contrary to OutRun on arcade, when entering your name on the high-score list, once you enter the last letter, the selector doesn't jump to "ED", giving you the opportunity to go to the backspace arrow, in case you entered the wrong letter. Instead, the entry is instantly validated with no possibility of correcting mistakes. I end up editing the .xml by hand regularly because of that :)

**Comment by djyt** [comment]
Actually, it matches the (original) arcade version.

We fixed this behaviour in Enhanced Edition, and I just haven't brought the changes over, but I will do at some point.

**Comment by yepyepyep4711** [comment]
> Actually, it matches the (original) arcade version.
> 
> We fixed this behaviour in Enhanced Edition, and I just haven't brought the changes over, but I will do at some point.

arrgh, my bad. I forgot I was comparing this to the Enhanced Edition. Great to hear it will come!

**Comment by djyt** [comment]
79ce5dd 

Two tweaks in this commit:
1/ Ability to (optionally) enable last initial deletion in config.xml
2/ Ability to override the timer on the high-score screen with a different value. Personally, I find the default a little short!

**Comment by yepyepyep4711** [comment]
that was fast! Awesome!

**Comment by djyt** [comment]
Yep, it will be in the next release. Or if you're impatient feel free to compile it yourself now! :)
