### ISSUE TITLE
issues with opr-10188.71f

### ISSUE THREAD

**Issue by yepyepyep4711** [djyt/cannonball#92]
Hello,

there seems to be an error in the CRC check of opr-10188.71f. If I don't deactivate CRC check, I get an "unable to locate" error for that file. If I do, I can start the program, but get:
opr-10188.71f has incorrect checksum.
Expected: 37598616 Found: c2de09b2

Note that in the game, the file works as intended. I can switch between fixed and unfixed samples and hear the difference.

Is it maybe looking for the CRC of a rom patched with the patch from 2013? I'm using the one from 2020.

**Comment by djyt** [comment]
Yep the 2020 patch isn't supported yet, but will be in the next release.

**Comment by djyt** [comment]
Fixed in checkin: 0f3fabcb80682c34487eb68cbf91ec6d8884b54d
