### ISSUE TITLE
[Feature Request] Option to use extra music tracks from OutRun: Enhanced Edition

### ISSUE THREAD

**Issue by FreshRoyal** [djyt/cannonball#99]
I really like this project, and it's my favorite way to play OutRun.

Would it be possible to add the ability to use the three extra music tracks from Enhanced Edition? Maybe it could require those ROM files to be able to play them. If possible, maybe even add the ability to add custom tracksbeyond that, as in not even replacing the original tracks.

Thank you for your time

**Comment by djyt** [comment]
It's already possible to use the new music, by extracting the binary data from the 3DS/Switch versions. I appreciate this isn't trivial for most people, but there isn't really an easy way of providing this legally. You've got to extract it yourself. 

The Enhanced ROMs are intended for original hardware only, and I'm not looking to muddy the waters by making them available for emulation or use in CannonBall as Sega are currently selling OutRun on the Switch and 3DS stores.

**Comment by FreshRoyal** [comment]
Sorry to bother, but I already extracted a CIA of 3D OutRun. What files from it do I use and how do I format them in the ROMs folder?

**Comment by djyt** [comment]
I wrote some brief information here:
https://github.com/djyt/cannonball/wiki/Extracting-OutRun-Music-From-the-Switch-&-3DS

**Comment by FreshRoyal** [comment]
So, I've swapped to trying to get the binaries from the Switch release, and I was able to get the streamed music and convert it to WAVs just fine, and the executable is decompressed. I'm having issues actually locating the offsets in which they are located. Do I use a hex editor such as HxD? I tried doing it, but it says the listed offsets are in the wrong format.

**Comment by djyt** [comment]
Yeah, use a hex editor and copy and paste the specified length of binary data into a new file. 

Note, that I've no idea how many revisions of the Switch game there are out there. I'm aware of two, for which I provided the offsets. It's possible there are more versions... 

![image](https://user-images.githubusercontent.com/2414449/117012076-74628000-ace6-11eb-9454-374d97212fd8.png)

**Comment by FreshRoyal** [comment]
Thank you so much for your help so far. I do have version 1.1, and I was able to locate Cruising Lane. Problem is, when I try to load it into Cannonball, it crashes. Do I just copy and paste the values to a new file and save it as a .bin? The size and CRC32 match up with yours. I also went ahead and switched to using Hex Editor Neo because HxD was giving me issues.

**Comment by djyt** [comment]
Cool, glad you got it working! If you feel you can explain the process more clearly to others than myself, then please do - or even post a guide in the Discussions area :)
